### PR TITLE
Adding customization for firefox

### PR DESCRIPTION
**Pull request by wlayzz**
Hi ! :wave: 
With @Skileau we worked on the issue #90, here is a first PR with a firefox customized by default.
Adding pre-installed addons, change default theme to dark, add bookmarks. :fox_face: 

### Add-on added:
- foxyproxy-standard
- darkreader
- uaswitcher
- cookie-editor
- wappalyzer

> To install other addons, add the link of the addon from the Mozilla store to the array in setup.py (ex: https://addons.mozilla.org/fr/firefox/addon/foxyproxy-standard/).

### Bookmarks is on the places.sqlite:
- https://exegol.readthedocs.io/en/latest/
- https://www.thehacker.recipes/
- https://tools.thehacker.recipes/
- https://book.hacktricks.xyz/welcome/readme
- https://github.com/swisskyrepo/PayloadsAllTheThings
- https://www.hackthebox.com/
- https://www.ired.team/

> To add new bookmark, open firefox, flush the history, add bookmarks to the current firefox session, close firefox and create a backup of `places.sqlite` located in `/root/.mozilla/firefox/*.Exegol/places.sqlite` with the command `sqlite3 /root/.mozilla/firefox/*.Exegol/places.sqlite ".backup /workspace/places.sqlite"`. Then replace the `places.sqlite` in the  firefox folder of this repository.

image

### CODE REVIEW

**Comment by ShutdownRepo** [comment]
Nice one! Did you manage to trust Burp's CA as well?

**Comment by wlayzz** [comment]
No it stays in the todos for now, we will try to look into it later.

**Comment by Dramelac** [comment]
> Nice one! Did you manage to trust Burp's CA as well?

I don't think it's a good idea to generate the burp certificate when building the image and add it to the browser, it's a very big weakness to have a trusted public CA in a browser. 
I don't know exactly when Burp generates its CA but for me it should stay local during the container creation to keep the private and unique side to each profile. 

So ideally this setup should be done by the entrypoint when creating a new container (by the load_supported_setups.sh I think)

**Comment by QU35T-code** [comment]
Installing the `jadx` tool from the pipeline didn't work here due to an update to the jadx source repo during testing :

https://github.com/skylot/jadx/actions/runs/4285932497/jobs/7464839178

image

Commit : dd51783

So the problem is not related to the installation of `firefox`.

**Comment by ShutdownRepo** [comment]
> > Nice one! Did you manage to trust Burp's CA as well?
> 
> I don't think it's a good idea to generate the burp certificate when building the image and add it to the browser, it's a very big weakness to have a trusted public CA in a browser. I don't know exactly when Burp generates its CA but for me it should stay local during the container creation to keep the private and unique side to each profile.
> 
> So ideally this setup should be done by the entrypoint when creating a new container (by the `load_supported_setups.sh` I think)

Agreed, let's make it part of the container creation process, instead of image build

**Comment by ShutdownRepo** [comment]
@wlayzz do you still want to work things out on this PR or is it ready for merge on your end?

**Comment by wlayzz** [comment]
> @wlayzz do you still want to work things out on this PR or is it ready for merge on your end?

This can be merge as a first iteration, we will continue to improve this feature with other PR laters :smiley:

**Review by ShutdownRepo — APPROVED** [review]
Approving the PR, latests checks are failing due to unrelated network issues

**Pull request merged**
