### PR TITLE
Fix checksec-py lief version

### PR DESCRIPTION
**Pull request by QU35T-code**
# Description

Increase temp fix limit (mobsf)
Fix lief version for checksec-py

image

### CODE REVIEW

**Comment by QU35T-code** [comment]
@ShutdownRepo -

Duplicate #300 - I let you choose which PR merge

**Comment by QU35T-code** [comment]
Build works fine ! Merge incoming

**Comment by ShutdownRepo** [comment]
@QU35T-code I like better #300 because it's dynamic and greps for linux builds
Can you review #300?

**Comment by QU35T-code** [comment]
You mean #291 ?

**Pull request merged**
