### PR TITLE
Update faketime history

### PR DESCRIPTION
**Pull request by Sh3llch0k**
Added in history lazier cmd to faketime with rdate

# Description

> Added a command in history that allows to faketime exactly at the time of a target, combining it with rdate. No more approximative faketime! We are too lazy for that!

### CODE REVIEW

**Review by ShutdownRepo — APPROVED** [review]

**Comment by ShutdownRepo** [comment]
Awesome! We love lazy

**Comment by ShutdownRepo** [comment]
I changed the target branch, I realized it wasn't the right one
Please resolve the conflict before merging

**Comment by QU35T-code** [comment]
@ShutdownRepo,

We also have a similar command -> https://github.com/ThePorgs/Exegol-images/pull/359/files
Do you think we should leave the 2, otherwise which one to keep ?

**Comment by ShutdownRepo** [comment]
> @ShutdownRepo,
> 
> We also have a similar command -> https://github.com/ThePorgs/Exegol-images/pull/359/files Do you think we should leave the 2, otherwise which one to keep ?

you're right, let's keep one at the moment. I noticed our current command is probably missing `zsh` at the end though

**Pull request closed without merging**
