### PR TITLE
New tools - August 2023

### PR DESCRIPTION
**Pull request by QU35T-code**
# Description

Added new tools requested by the community.

[Chainsaw](https://github.com/WithSecureLabs/chainsaw)
[RsaCracker](https://github.com/skyf0l/RsaCracker)
[ppfinder](https://github.com/yeswehack/pp-finder)
[Azure-cli](https://github.com/Azure/azure-cli)
[tig](https://github.com/jonas/tig)
[ROADtools](https://github.com/dirkjanm/ROADtools)
[GoMapEnum](https://github.com/nodauf/GoMapEnum)
[yalis](https://github.com/EatonChips/yalis)
[TeamsPhisher](https://github.com/Octoberfest7/TeamsPhisher)
[sherlock](https://github.com/sherlock-project/sherlock)
[blackbird](https://github.com/p1ngul1n0/blackbird)
[MurMurHash](https://github.com/QU35T-code/MurMurHash/tree/main)
[GeoPincer](https://github.com/tloja/GeoPincer)
[censys-python](https://github.com/censys/censys-python)
[yt-dlp](https://github.com/yt-dlp/yt-dlp)

Added ftp-server alias and history for python simple smtp server

### CODE REVIEW

**Comment by ShutdownRepo** [comment]
Can you synchronize with latest changes on `dev`, pipeline was failing because of an update on `dex2jar`

**Comment by ShutdownRepo** [comment]
Pipeline fails with
```
Failed command: ls "/lib/node_modules/pp-finder"
Standard output:
    Your version of Exegol wrapper is not up-to-date!
    
Standard error:
    ls: cannot access '/lib/node_modules/pp-finder': No such file or directory
```

**Comment by QU35T-code** [comment]
I let you review @ShutdownRepo and merge ;)

**Review by ShutdownRepo — CHANGES_REQUESTED** [review]
Let’s have python aliases in the following format
- tool.py : for all aliases
- tool : when there is a wrapper above the tool.py, like grc/proxychains/etc.

**Comment by QU35T-code** [comment]
I'm going to update this PR, we'll open a ticket to do it on all the other tools.

**Comment by ShutdownRepo** [comment]
Deal 🤝

**Pull request merged**
