### PR TITLE
Added Bloodhound Custom Queries for ESC9

### PR DESCRIPTION
**Pull request by xl00t**
# Description

> Added Bloodhound Custom Queries for ESC9. Taken from [https://github.com/ly4k/Certipy/blob/main/customqueries.json#L185-L214](https://github.com/ly4k/Certipy/blob/main/customqueries.json#L185-L214
)

### CODE REVIEW

**Review by ShutdownRepo — APPROVED** [review]

**Comment by ShutdownRepo** [comment]
Thank you for the pull request ! LGTM

**Review by Dramelac — CHANGES_REQUESTED** [review]
Change deplicate name

**Comment by Dramelac** [comment]
Noo @ShutdownRepo trop rapide x)

**Comment by Dramelac** [comment]
Pas grave je vais aller les edit à la main

**Pull request merged**
