### PR TITLE
Remove infoga

### PR DESCRIPTION
**Pull request by compass-dexter**
The repo dissappeared, https://github.com/m4ll0k/Infoga gives a 404.

# Description

The build fails now because the repo disappeared.

# Related issues

> If your PR responds to an issue for a bug fix or feature request, make sure to includes references to the issues (e.g. "fixes #xxxx").

# Point of attention

> Things you are not sure about that deserve special attention if you have doubts or questions.

### CODE REVIEW

**Review by QU35T-code — APPROVED** [review]

**Comment by ShutdownRepo** [comment]
Indeed, we commented it out in #216
I think the best course of action would be to wait and see if the repo resurfaces at some point, or if a fork show up. In that situation, we'll have the code ready. We could also limit this in time to make sure we remove the code in 2 months ([like this](https://exegol.readthedocs.io/en/dev/community/contributors.html#temporary-fixing-a-tool)) if there's still nothing

**Comment by compass-dexter** [comment]
> Indeed, we commented it out in https://github.com/ThePorgs/Exegol-images/pull/216

Oh I missed that :smile:
If you want you can close this PR.

**Comment by ShutdownRepo** [comment]
Keeping it on hold and duplicate for now, we'll see what we do about #216 😄

**Comment by ShutdownRepo** [comment]
Closing here, we'll keep it commented in the code in case a fork comes up some day

**Pull request closed without merging**
