### PR TITLE
fix: change temurin11 url

### LINKED ISSUE #291: [BUG] `install_java11` fails because only mac binaries are in the latest release
### Describe the bug

The latest release of adoptium/temurin11-binaries (https://github.com/adoptium/temurin11-binaries/releases/tag/jdk-11.0.22%2B7.1) only contains mac binaries. Therefore the build fails.

Instead of using https://api.github.com/repos/adoptium/temurin11-binaries/releases/latest in [package_base.sh](https://github.com/ThePorgs/Exegol-images/blob/main/sources/install/package_base.sh#L324) we should use https://api.github.com/repos/adoptium/temurin11-binaries/releases and pipe it to `sort | tail -n1`.

### Steps To Reproduce

1. Build the image and wait until `install_java11` is called.

### Exegol Wrapper Version

```Text
N/A
```

### Exegol container information

```Text
N/A
```

### Exception

_No response_

### Additional context

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by compass-dexter**
latest release does not always contain all expected binaries

fixes #291

### CODE REVIEW

**Review by ShutdownRepo — APPROVED** [review]

**Comment by ShutdownRepo** [comment]
Thank you! However the target branch of the PR is wrong, it should be `dev`, changing now

**Comment by ShutdownRepo** [comment]
Now that the branch is changed, can you push a change, whatever it is, to reload the Pull Request and have the right CI/CD check available?

**Comment by compass-dexter** [comment]
Rebased onto latest dev commit

**Comment by compass-dexter** [comment]
> Pipeline fails at Bloodhound-CE install, any idea to why?

No real clue. I rebased again and push, let's hope for the best.

**Comment by compass-dexter** [comment]
It's failing on `RsaCracker` now. I don't think it is related to this PR.

```
2024-01-29T11:15:17.1884252Z #29 62.78 error[E0599]: no method named `to_digits` found for struct `rug::Integer` in the current scope
2024-01-29T11:15:17.1885281Z #29 62.78    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rsacracker-0.6.5/src/key.rs:108:53
2024-01-29T11:15:17.1885764Z #29 62.78     |
2024-01-29T11:15:17.1886121Z #29 62.78 108 |             openssl::bn::BigNum::from_slice(&self.n.to_digits(Order::Msf)).unwrap(),
2024-01-29T11:15:17.1886660Z #29 62.78     |                                                     ^^^^^^^^^ help: there is a method with a similar name: `write_digits`
2024-01-29T11:15:17.1887020Z #29 62.78 
2024-01-29T11:15:17.3385897Z #29 62.79 error[E0599]: no method named `to_digits` found for struct `rug::Integer` in the current scope
2024-01-29T11:15:17.3387054Z #29 62.79    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rsacracker-0.6.5/src/key.rs:109:53
2024-01-29T11:15:17.3387497Z #29 62.79     |
2024-01-29T11:15:17.3387993Z #29 62.79 109 |             openssl::bn::BigNum::from_slice(&self.e.to_digits(Order::Msf)).unwrap(),
2024-01-29T11:15:17.3390654Z #29 62.79     |                                                     ^^^^^^^^^ help: there is a method with a similar name: `write_digits`
2024-01-29T11:15:17.3391227Z #29 62.79 
2024-01-29T11:15:17.3391808Z #29 62.79 error[E0599]: no method named `to_digits` found for struct `rug::Integer` in the current scope
2024-01-29T11:15:17.3392760Z #29 62.79    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rsacracker-0.6.5/src/key.rs:110:53
2024-01-29T11:15:17.3393199Z #29 62.79     |
2024-01-29T11:15:17.3393521Z #29 62.79 110 |             openssl::bn::BigNum::from_slice(&self.d.to_digits(Order::Msf)).unwrap(),
2024-01-29T11:15:17.3394039Z #29 62.79     |                                                     ^^^^^^^^^ help: there is a method with a similar name: `write_digits`
2024-01-29T11:15:17.3394391Z #29 62.79 
2024-01-29T11:15:17.3394735Z #29 62.80 error[E0599]: no method named `to_digits` found for struct `rug::Integer` in the current scope
2024-01-29T11:15:17.3395442Z #29 62.80    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rsacracker-0.6.5/src/key.rs:114:55
2024-01-29T11:15:17.3395870Z #29 62.80     |
2024-01-29T11:15:17.3396196Z #29 62.80 114 |             openssl::bn::BigNum::from_slice(&self.p().to_digits(Order::Msf)).unwrap(),
2024-01-29T11:15:17.3396714Z #29 62.80     |                                                       ^^^^^^^^^ help: there is a method with a similar name: `write_digits`
2024-01-29T11:15:17.3397054Z #29 62.80 
2024-01-29T11:15:17.3397398Z #29 62.81 error[E0599]: no method named `to_digits` found for struct `rug::Integer` in the current scope
2024-01-29T11:15:17.3398097Z #29 62.81    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rsacracker-0.6.5/src/key.rs:115:55
2024-01-29T11:15:17.3398521Z #29 62.81     |
2024-01-29T11:15:17.3399088Z #29 62.81 115 |             openssl::bn::BigNum::from_slice(&self.q().to_digits(Order::Msf)).unwrap(),
2024-01-29T11:15:17.3399659Z #29 62.81     |                                                       ^^^^^^^^^ help: there is a method with a similar name: `write_digits`
2024-01-29T11:15:17.3400005Z #29 62.81 
2024-01-29T11:15:17.3400352Z #29 62.81 error[E0599]: no method named `to_digits` found for struct `rug::Integer` in the current scope
2024-01-29T11:15:17.3401104Z #29 62.81    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rsacracker-0.6.5/src/key.rs:119:56
2024-01-29T11:15:17.3401571Z #29 62.81     |
2024-01-29T11:15:17.3401895Z #29 62.81 119 |             openssl::bn::BigNum::from_slice(&self.dp().to_digits(Order::Msf)).unwrap(),
2024-01-29T11:15:17.3402421Z #29 62.81     |                                                        ^^^^^^^^^ help: there is a method with a similar name: `write_digits`
2024-01-29T11:15:17.3402772Z #29 62.81 
2024-01-29T11:15:17.3403116Z #29 62.82 error[E0599]: no method named `to_digits` found for struct `rug::Integer` in the current scope
2024-01-29T11:15:17.3403831Z #29 62.82    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rsacracker-0.6.5/src/key.rs:120:56
2024-01-29T11:15:17.3404272Z #29 62.82     |
2024-01-29T11:15:17.3404600Z #29 62.82 120 |             openssl::bn::BigNum::from_slice(&self.dq().to_digits(Order::Msf)).unwrap(),
2024-01-29T11:15:17.3405128Z #29 62.82     |                                                        ^^^^^^^^^ help: there is a method with a similar name: `write_digits`
2024-01-29T11:15:17.3405480Z #29 62.82 
2024-01-29T11:15:17.3405827Z #29 62.83 error[E0599]: no method named `to_digits` found for struct `rug::Integer` in the current scope
2024-01-29T11:15:17.3406533Z #29 62.83    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rsacracker-0.6.5/src/key.rs:121:58
2024-01-29T11:15:17.3406972Z #29 62.83     |
2024-01-29T11:15:17.3407312Z #29 62.83 121 |             openssl::bn::BigNum::from_slice(&self.qinv().to_digits(Order::Msf)).unwrap(),
2024-01-29T11:15:17.3407836Z #29 62.83     |                                                          ^^^^^^^^^ help: there is a method with a similar name: `write_digits`
2024-01-29T11:15:17.3408185Z #29 62.83 
2024-01-29T11:15:17.3408786Z #29 62.85 For more information about this error, try `rustc --explain E0599`.
2024-01-29T11:15:17.3409406Z #29 62.85 error: could not compile `rsacracker` (lib) due to 8 previous errors
2024-01-29T11:15:17.3409863Z #29 62.85 warning: build failed, waiting for other jobs to finish...
```

**Comment by QU35T-code** [comment]
Hello @compass-dexter, can you sync with dev please (merge with dev)

**Review by QU35T-code — APPROVED** [review]

**Comment by ShutdownRepo** [comment]
Thank you @compass-dexter, and @QU35T-code for the review !

**Pull request merged**
