### PR TITLE
New tool creds

### PR DESCRIPTION
**Pull request by lap1nou**
# Description

This aim to add a tool called `creds` (https://github.com/ihebski/DefaultCreds-cheat-sheet). This tool can be used to quickly search for default credentials:

```
$ creds search tomcat

+----------------------------------+------------+------------+
| Product                          |  username  |  password  |
+----------------------------------+------------+------------+
| apache tomcat host manager (web) |   admin    |   admin    |
| apache tomcat host manager (web) |   ADMIN    |   ADMIN    |
| apache tomcat host manager (web) |   admin    |  <blank>   |
| apache tomcat host manager (web) |   admin    |   j5Brn9   |
| apache tomcat host manager (web) |   admin    |   tomcat   |
| apache tomcat host manager (web) |   cxsdk    |   kdsxc    |
| apache tomcat host manager (web) | j2deployer | j2deployer |
| apache tomcat host manager (web) |  ovwebusr  | OvW*busr1  |
| apache tomcat host manager (web) |    QCC     |  QLogic66  |
| apache tomcat host manager (web) |   role1    |   role1    |
| apache tomcat host manager (web) |   role1    |   tomcat   |
| apache tomcat host manager (web) |    role    | changethis |
| apache tomcat host manager (web) |    root    |    root    |
| apache tomcat host manager (web) |   tomcat   | changethis |
| apache tomcat host manager (web) |   tomcat   |   s3cret   |
| apache tomcat host manager (web) |   tomcat   |   tomcat   |
| apache tomcat host manager (web) |   xampp    |   xampp    |
+----------------------------------+------------+------------+
```

# Related issues

N / A

# Point of attention

N / A

### CODE REVIEW

**Comment by ShutdownRepo** [comment]
Thank you for the addition! Running the pipeline now

**Comment by lap1nou** [comment]
`shellcheck` is failling because I tried to implement the version for the function (https://github.com/ThePorgs/Exegol-images/pull/302), how would you recommend changing my code ? I tried to mimic this: https://github.com/ThePorgs/Exegol-images/blob/205b01d6620c3d4bc0d5d0ce9dc48730c54498e6/sources/install/package_base.sh#L159

**Comment by QU35T-code** [comment]
You can delete the version for now. I will add it later.

**Review by QU35T-code — APPROVED** [review]

**Comment by ShutdownRepo** [comment]
@lap1nou do you mind merging latest dev changes into your branch so that I can run the pipeline?

**Review by QU35T-code — APPROVED** [review]

**Comment by QU35T-code** [comment]
Pipeline in progress

**Review by ShutdownRepo — APPROVED** [review]

**Pull request merged**
