### PR TITLE
Improve Sharphound and Azurehound installations

### PR DESCRIPTION
**Pull request by gbe**
Howdy,

this PR aims at improving the installation of the ingestors Sharphound and Azurehound for Bloodhound-CE:
- the case of local variables is switched from uppercase to lowercase for consistency across Exegol
- local paths are put into a variable instead of repeating each time the same paths
- instead of Curling the same Github page several times, the result is put once into a `temporary file`
- instead of `Grepping` the json output of Github, the temporary file is parsed with `jq`
- fix the variable `azurehound_url_amd64` that was containing the `arm64` URL, and the other way around the arm64 variable contained the amd64 URL
- A sha256 file was computed locally but nothing was done with it. Instead, the sha256files for Azurehound are downloaded from Github and the integrity of the zip archives is check prior to unzipping them.
- As upstream does not provide a sha256 file for Sharphound, the file computed locally is removed in order to not give a false impression that it was downloaded from Github.

### CODE REVIEW

**Review by QU35T-code — APPROVED** [review]

**Comment by QU35T-code** [comment]
@gbe,

Can you fix shell check ? Thanks !

https://github.com/ThePorgs/Exegol-images/actions/runs/11519348571/job/32171164045

**Comment by gbe** [comment]
@QU35T-code Hopefully I understood what shell check complained about, and fix it.

**Comment by gbe** [comment]
@QU35T-code Could you restart the pipeline to confirm that Exegol builds fine?

**Comment by QU35T-code** [comment]
Done @gbe Thanks

**Comment by QU35T-code** [comment]
@gbe can you fix shellcheck ? I will fix temp fix

**Comment by gbe** [comment]
@QU35T-code It's done. Can you run the check again please? Thanks

**Pull request merged**
