### PR TITLE
Reduce image size by adding flag depth 1 when git cloning

### PR DESCRIPTION
**Pull request by gbe**
I noticed that some tools missed the flag `--depth 1` for `git clone`.

For some tools, it was simply forgotten.

For others, the flag --depth 1 was removed for temp fixes reasons.
This PR reinstates the depth flag to clone directly the appropriate branch in a single command instead of doing a `git clone` followed by a `git checkout`:

- Example with sliver: `git -C /opt/tools/ clone --branch v1.5.41 --depth 1 https://github.com/BishopFox/sliver.git`

- Another with Bloodhound-CE: `git -C /opt/tools/ clone --branch bloodhound-ce --depth 1 https://github.com/dirkjanm/BloodHound.py BloodHound-CE.py`

About sliver, I moved the temp fix criticalecho at the beginning of the function to only clone the repo if the date condition is met. I hope it's ok like this.

### CODE REVIEW

**Review by ShutdownRepo — APPROVED** [review]

**Comment by QU35T-code** [comment]
I have to check but it may be a deliberate "miss". I have to check if it works even if we add depth 1

**Comment by QU35T-code** [comment]
Let’s see what the runners think 😄

**Comment by QU35T-code** [comment]
Hey @gbe,

Can you push a commit to sync the pipeline ?

**Comment by gbe** [comment]
Done

**Review by QU35T-code — APPROVED** [review]

**Comment by QU35T-code** [comment]
Pipeline is ok ☑️

**Review by ShutdownRepo — APPROVED** [review]

**Pull request merged**
