### PR TITLE
Add microsoft-rpc-fuzzing-tools by p0dalirius

### PR DESCRIPTION
**Pull request by Fisjkars**
Add [microsoft-rpc-fuzzing-tools](https://github.com/p0dalirius/microsoft-rpc-fuzzing-tools)

### CODE REVIEW

**Comment by ShutdownRepo** [comment]
Thank you for this pull request. I may be wrong but iirc, this set of tools is used for research and it's probably more relevant to pull it when needed instead of featuring it by default on all Exegol images. @p0dalirius what do you think?

**Comment by p0dalirius** [comment]
Hi, thanks for the proposal @Fisjkars!
I think it is not useful for most of Exegol users as most of them are not doing research. If someone needs it they will git clone it but I don't think it is necessary to add it directly into exegol

**Comment by ShutdownRepo** [comment]
> Hi, thanks for the proposal @Fisjkars! I think it is not useful for most of Exegol users as most of them are not doing research. If someone needs it they will git clone it but I don't think it is necessary to add it directly into exegol

Ok it confirms what I had in mind, thank you for (fastest ever) comment!

**Comment by Dramelac** [comment]
Just a tips/reminder in case of but if you need such tools on every exegol container you create you can install it automatically using [my-resources](https://exegol.readthedocs.io/en/latest/exegol-image/my-resources.html) ;)

Have a nice day!

**Pull request closed without merging**
